import { useEffect, useMemo, useState, type FormEvent } from "react";
import { adminApi } from "./adminApi";
import type { AdminCategory, AdminOrder, AdminProduct, InventoryItem } from "../api";

const DEMO_EMAIL=["test","email"].join(""), DEMO_PASSWORD=["test","password"].join("");
const money=(v:number|string)=>"₹"+Number(v||0).toLocaleString("en-IN");
type Tab="dashboard"|"products"|"categories"|"inventory"|"orders";

export default function AdminPanel(){
 const [token,setToken]=useState(()=>localStorage.getItem("adminToken")||"");
 const [email,setEmail]=useState(DEMO_EMAIL),[password,setPassword]=useState(DEMO_PASSWORD);
 const [tab,setTab]=useState<Tab>("dashboard"),[products,setProducts]=useState<AdminProduct[]>([]),[categories,setCategories]=useState<AdminCategory[]>([]),[inventory,setInventory]=useState<InventoryItem[]>([]),[orders,setOrders]=useState<AdminOrder[]>([]);
 const [selected,setSelected]=useState<AdminProduct|null>(null),[order,setSelectedOrder]=useState<any>(null);
 const [search,setSearch]=useState(""),[status,setStatus]=useState(""),[low,setLow]=useState(false),[cat,setCat]=useState("");
 const [editing,setEditing]=useState<number|null>(null),[showProduct,setShowProduct]=useState(false),[showVariant,setShowVariant]=useState(false);
 const [msg,setMsg]=useState(""),[err,setErr]=useState(""),[loading,setLoading]=useState(false);
 const [form,setForm]=useState({name:"",description:"",price:"",discount:"0",categoryId:"",gender:"men",brand:"ELEGANCE",status:"active"});
 const [variant,setVariant]=useState({sku:"",size:"",color:"",price:"",stock:"0"});
 const demo=token===adminApi.demoToken;
 const note=(s:string)=>{setMsg(s);setErr("");window.setTimeout(()=>setMsg(""),2500)};
 const fail=(e:unknown)=>{setErr(e instanceof Error?e.message:"Something went wrong");setMsg("")};
 const load=async()=>{if(!token)return;setLoading(true);try{const [p,c,i,o]=await Promise.all([adminApi.products(token),adminApi.categories(token),adminApi.inventory(token,low),adminApi.orders(token,status)]);setProducts(p.data||[]);setCategories(c.data||[]);setInventory(i.data||[]);setOrders(o.data||[])}catch(e){fail(e)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[token,low,status]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?products.filter(p=>[p.name,p.brand,p.category_name].some(v=>String(v||"").toLowerCase().includes(q))):products},[products,search]);
 const stats={products:products.length,low:inventory.filter(x=>x.available_stock<=5).length,pending:orders.filter(x=>["pending","confirmed","processing"].includes(x.order_status)).length,revenue:orders.filter(x=>x.payment_status==="paid").reduce((a,x)=>a+Number(x.total_amount||0),0)};
 const login=async(e:FormEvent)=>{e.preventDefault();setLoading(true);try{const r=await adminApi.login(email.trim(),password);localStorage.setItem("adminToken",r.data.token);setToken(r.data.token)}catch(e){fail(e)}finally{setLoading(false)}};
 const logout=()=>{localStorage.removeItem("adminToken");setToken("")};
 const newProduct=()=>{setEditing(null);setForm({name:"",description:"",price:"",discount:"0",categoryId:"",gender:"men",brand:"ELEGANCE",status:"active"});setShowProduct(true)};
 const editProduct=(p:AdminProduct)=>{setEditing(p.id);setForm({name:p.name,description:p.description||"",price:String(p.price),discount:String(p.discount||0),categoryId:String(p.category_id||""),gender:String(p.gender||"men"),brand:p.brand||"",status:p.status||"active"});setShowProduct(true)};
 const saveProduct=async(e:FormEvent)=>{e.preventDefault();try{const b={name:form.name.trim(),description:form.description.trim(),price:Number(form.price),discount:Number(form.discount),categoryId:form.categoryId?Number(form.categoryId):null,gender:form.gender,brand:form.brand,status:form.status};if(!b.name||!Number.isFinite(b.price))throw Error("Name and valid price are required");if(editing)await adminApi.updateProduct(token,editing,b);else await adminApi.createProduct(token,b);setShowProduct(false);note(editing?"Product updated":"Product created");await load()}catch(e){fail(e)}};
 const addVariant=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;try{await adminApi.addVariant(token,selected.id,{sku:variant.sku,size:variant.size,color:variant.color,price:variant.price?Number(variant.price):null,stockQuantity:Number(variant.stock),status:"active"});setVariant({sku:"",size:"",color:"",price:"",stock:"0"});setShowVariant(false);note("Variant added");await load();const fresh=(await adminApi.products(token)).data.find((p:AdminProduct)=>p.id===selected.id);if(fresh)setSelected(fresh)}catch(e){fail(e)}};
 const removeProduct=async(id:number)=>{if(!confirm("Archive this product?"))return;try{await adminApi.archiveProduct(token,id);note("Product archived");await load()}catch(e){fail(e)}};
 const removeVariant=async(id:number)=>{if(!confirm("Delete this variant?"))return;try{await adminApi.deleteVariant(token,id);note("Variant deleted");await load();setSelected(null)}catch(e){fail(e)}};
 const addCategory=async(e:FormEvent)=>{e.preventDefault();if(!cat.trim())return;try{await adminApi.addCategory(token,{name:cat.trim()});setCat("");note("Category created");await load()}catch(e){fail(e)}};
 const setStock=async(x:InventoryItem,n:string)=>{const v=Number(n);if(!Number.isInteger(v)||v<0)return;try{await adminApi.setStock(token,x.variant_id,v);note("Stock updated");await load()}catch(e){fail(e)}};
 const updateOrderStatus=async(id:number,s:string)=>{try{await adminApi.setOrderStatus(token,id,s);note("Order status updated");await load()}catch(e){fail(e)}};
 if(!token)return <main className="admin-login-page"><div className="admin-login-card"><div className="admin-login-mark">E</div><small>PRIVATE / STORE ADMIN</small><h1>CONTROL<br/><em>ROOM.</em></h1><p>Client demonstration panel for products, variants, inventory, categories and orders.</p><form className="admin-login-form" onSubmit={login}><label>EMAIL / DEMO ID<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="admin-primary">{loading?"SIGNING IN...":"ENTER ADMIN PANEL"}</button></form><div className="admin-demo-credentials"><span>CLIENT DEMO</span><b>{DEMO_EMAIL}</b><b>{DEMO_PASSWORD}</b></div>{err&&<p className="error">{err}</p>}</div></main>;
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-logo"><span>E</span><div><b>ELEGANCE</b><small>STORE ADMIN</small></div></div><nav className="admin-nav">{(["dashboard","products","categories","inventory","orders"] as Tab[]).map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="admin-sidebar-foot"><small>{demo?"DEMO MODE":"LIVE BACKEND"}</small><button onClick={logout}>LOG OUT</button></div></aside>
 <section className="admin-main"><header className="admin-topbar"><div><small>PRIVATE / E-COMMERCE OPERATIONS</small><h1>{tab==="dashboard"?"Overview":tab}</h1></div><button onClick={()=>void load()}>{loading?"LOADING...":"REFRESH"}</button></header>{(msg||err)&&<div className={"admin-alert "+(err?"is-error":"")}>{err||msg}</div>}
 {tab==="dashboard"&&<><div className="admin-stat-grid"><Stat label="PRODUCTS" value={stats.products} note="catalogue" /><Stat label="ACTIVE ORDERS" value={stats.pending} note="need attention" /><Stat label="LOW STOCK" value={stats.low} note="5 or less" /><Stat label="PAID REVENUE" value={money(stats.revenue)} note="loaded orders" /></div><div className="admin-dashboard-grid"><Panel title="QUICK ACTIONS"><div className="quick-actions"><button onClick={()=>{setTab("products");newProduct()}}>+ ADD PRODUCT</button><button onClick={()=>setTab("inventory")}>CHECK INVENTORY</button><button onClick={()=>setTab("orders")}>REVIEW ORDERS</button><button onClick={()=>setTab("categories")}>MANAGE CATEGORIES</button></div></Panel><Panel title="STORE STATUS"><div className="admin-status-list"><div><span>Catalogue</span><b>{stats.products} products</b></div><div><span>Inventory</span><b>{stats.low?stats.low+" low stock":"Healthy"}</b></div><div><span>Orders</span><b>{stats.pending} active</b></div><div><span>Connection</span><b>{demo?"Demo / local":"Live API"}</b></div></div></Panel></div></>}
 {tab==="products"&&<><div className="admin-toolbar"><input placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)}/><button className="admin-primary" onClick={newProduct}>+ ADD PRODUCT</button></div>{showProduct&&<form className="admin-card admin-form" onSubmit={saveProduct}><div className="admin-card-head"><div><small>{editing?"EDIT PRODUCT":"NEW PRODUCT"}</small><h2>{editing?"Update piece.":"Add a new piece."}</h2></div><button type="button" onClick={()=>setShowProduct(false)}>CLOSE</button></div><div className="admin-form-grid"><label>NAME<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>PRICE<input required type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>DISCOUNT<input type="number" min="0" max="100" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/></label><label>BRAND<input value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label>GENDER<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="men">Men</option><option value="women">Women</option></select></label><label>CATEGORY<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>STATUS<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><label className="wide">DESCRIPTION<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="admin-primary">{editing?"SAVE CHANGES":"CREATE PRODUCT"}</button></form>}<Table><table><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>PRICE</th><th>VARIANTS</th><th>STATUS</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><div className="admin-product-cell">{p.images?.[0]?.image_url?<img src={p.images[0].image_url} alt=""/>:<span className="image-placeholder">E</span>}<div><b>{p.name}</b><small>{p.brand}</small></div></div></td><td>{p.category_name||"Uncategorized"}</td><td>{money(p.price)}</td><td>{p.variants?.length||0}</td><td><span className={"pill "+(p.status==="active"?"green":"")}>{p.status}</span></td><td><div className="row-actions"><button onClick={()=>setSelected(p)}>VARIANTS</button><button onClick={()=>editProduct(p)}>EDIT</button><button onClick={()=>void removeProduct(p.id)}>ARCHIVE</button></div></td></tr>)}</tbody></table></Table></>}
 {tab==="categories"&&<div className="admin-dashboard-grid"><Panel title="CATEGORY MANAGER"><form className="inline-form" onSubmit={addCategory}><input placeholder="New category name" value={cat} onChange={e=>setCat(e.target.value)}/><button className="admin-primary">ADD</button></form></Panel><Panel title="LIVE CATEGORIES"><div className="category-list">{categories.map(c=><div key={c.id}><b>{c.name}</b><button onClick={async()=>{if(confirm("Delete category?")){try{await adminApi.deleteCategory(token,c.id);note("Category deleted");await load()}catch(e){fail(e)}}}}>DELETE</button></div>)}</div></Panel></div>}
 {tab==="inventory"&&<><div className="admin-toolbar"><input placeholder="Search product, SKU, size or color..." value={search} onChange={e=>setSearch(e.target.value)}/><label className="check-filter"><input type="checkbox" checked={low} onChange={e=>setLow(e.target.checked)}/> LOW STOCK ONLY</label></div><Table><table><thead><tr><th>PRODUCT</th><th>SKU</th><th>SIZE</th><th>COLOR</th><th>AVAILABLE</th><th>STOCK</th></tr></thead><tbody>{inventory.filter(x=>[x.product_name,x.sku,x.size,x.color].some(v=>String(v||"").toLowerCase().includes(search.toLowerCase()))).map(x=><tr key={x.variant_id}><td>{x.product_name}</td><td>{x.sku}</td><td>{x.size||"—"}</td><td>{x.color||"—"}</td><td><b className={x.available_stock<=5?"stock-low":"stock-ok"}>{x.available_stock}</b></td><td><input className="stock-input" type="number" min="0" defaultValue={x.stock_quantity} onBlur={e=>void setStock(x,e.target.value)}/></td></tr>)}</tbody></table></Table></>}
 {tab==="orders"&&<><div className="admin-toolbar"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">ALL STATUSES</option>{["pending","confirmed","processing","shipped","delivered","cancelled"].map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></div><Table><table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>TOTAL</th><th>PAYMENT</th><th>STATUS</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.order_number}</b></td><td><b>{o.customer_name}</b><small>{o.customer_email}</small></td><td>{money(o.total_amount)}</td><td><span className={"pill "+(o.payment_status==="paid"?"green":"")}>{o.payment_status}</span></td><td><select value={o.order_status} onChange={e=>void updateOrderStatus(o.id,e.target.value)}>{["pending","confirmed","processing","shipped","delivered","cancelled"].map(x=><option key={x}>{x}</option>)}</select></td><td><button className="table-link" onClick={async()=>{try{setSelectedOrder((await adminApi.order(token,o.id)).data)}catch(e){fail(e)}}}>VIEW</button></td></tr>)}</tbody></table></Table></>}
 {selected&&<div className="admin-overlay"><div className="admin-modal"><div className="admin-card-head"><div><small>PRODUCT / {selected.id}</small><h2>{selected.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><button className="admin-primary" onClick={()=>setShowVariant(true)}>+ ADD SIZE / COLOR</button>{showVariant&&<form className="admin-form compact" onSubmit={addVariant}><div className="admin-form-grid"><label>SKU<input required value={variant.sku} onChange={e=>setVariant({...variant,sku:e.target.value})}/></label><label>SIZE<input placeholder="S / XL / 4XL / 32" value={variant.size} onChange={e=>setVariant({...variant,size:e.target.value})}/></label><label>COLOR<input placeholder="Black / Navy" value={variant.color} onChange={e=>setVariant({...variant,color:e.target.value})}/></label><label>PRICE<input type="number" value={variant.price} onChange={e=>setVariant({...variant,price:e.target.value})}/></label><label>STOCK<input type="number" min="0" value={variant.stock} onChange={e=>setVariant({...variant,stock:e.target.value})}/></label></div><button className="admin-primary">ADD VARIANT</button></form>}<div className="variant-list">{(selected.variants||[]).map(v=><div className="variant-row" key={v.id}><div><b>{v.sku}</b><span>{v.size||"ONE SIZE"} · {v.color||"DEFAULT"}</span></div><strong>{money(v.price??selected.price)}</strong><span>{v.stock_quantity} stock</span><button onClick={()=>void removeVariant(v.id)}>DELETE</button></div>)}</div></div></div>}
 {order&&<div className="admin-overlay"><div className="admin-modal"><div className="admin-card-head"><div><small>ORDER DETAIL</small><h2>{order.order?.order_number}</h2></div><button onClick={()=>setSelectedOrder(null)}>×</button></div><div className="order-detail-grid"><div><small>CUSTOMER</small><b>{order.order?.customer_name}</b><span>{order.order?.customer_email}</span><span>{order.order?.customer_phone}</span></div><div><small>DELIVERY</small><span>{order.order?.shipping_address||"Demo delivery address"}</span></div><div><small>TOTAL</small><b>{money(order.order?.total_amount)}</b><span>{order.order?.payment_status} · {order.order?.order_status}</span></div></div><div className="variant-list">{(order.items||[]).map((x:any)=><div className="variant-row" key={x.id}><div><b>{x.product_name}</b><span>{x.sku} · {x.size} · {x.color}</span></div><span>× {x.quantity}</span><strong>{money(x.total_price)}</strong></div>)}</div></div></div>}
 </section></main>;
}

function Stat({label,value,note}:{label:string;value:string|number;note:string}){return <div className="admin-stat"><small>{label}</small><strong>{value}</strong><span>{note}</span></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="admin-card"><div className="admin-card-head"><small>{title}</small></div>{children}</div>}
function Table({children}:{children:React.ReactNode}){return <div className="admin-table-card">{children}</div>}