import { demoProducts, request, type AdminCategory, type AdminOrder, type AdminProduct, type InventoryItem } from "../api";
const DEMO_TOKEN="demo-admin-token", PKEY="demoAdminProducts", CKEY="demoAdminCategories", OKEY="demoAdminOrders";
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const isDemo=(t:string)=>t===DEMO_TOKEN;
function products():AdminProduct[]{const s=localStorage.getItem(PKEY);if(s)return JSON.parse(s);const v=clone(demoProducts) as AdminProduct[];localStorage.setItem(PKEY,JSON.stringify(v));return v}
function saveProducts(v:AdminProduct[]){localStorage.setItem(PKEY,JSON.stringify(v));return v}
function categories():AdminCategory[]{const s=localStorage.getItem(CKEY);if(s)return JSON.parse(s);const v:AdminCategory[]=[{id:1,name:"Men"},{id:2,name:"Women"},{id:3,name:"New Arrivals"},{id:4,name:"Sale"}];localStorage.setItem(CKEY,JSON.stringify(v));return v}
function saveCategories(v:AdminCategory[]){localStorage.setItem(CKEY,JSON.stringify(v));return v}
function orders():AdminOrder[]{const s=localStorage.getItem(OKEY);if(s)return JSON.parse(s);const now=Date.now();const v:AdminOrder[]=[{id:1,order_number:"DEMO-100241",customer_name:"Arjun Kumar",customer_email:"arjun@example.com",customer_phone:"9876543210",subtotal:5498,shipping_fee:0,discount_amount:0,total_amount:5498,payment_status:"paid",order_status:"processing",created_at:new Date(now-86400000).toISOString(),item_count:2},{id:2,order_number:"DEMO-100240",customer_name:"Sarah Thomas",customer_email:"sarah@example.com",customer_phone:"9876501234",subtotal:3999,shipping_fee:100,discount_amount:0,total_amount:4099,payment_status:"paid",order_status:"shipped",created_at:new Date(now-172800000).toISOString(),item_count:1},{id:3,order_number:"DEMO-100239",customer_name:"Rahul Menon",customer_email:"rahul@example.com",customer_phone:"9812345678",subtotal:2299,shipping_fee:100,discount_amount:0,total_amount:2399,payment_status:"pending",order_status:"pending",created_at:new Date(now-259200000).toISOString(),item_count:1}];localStorage.setItem(OKEY,JSON.stringify(v));return v}
function saveOrders(v:AdminOrder[]){localStorage.setItem(OKEY,JSON.stringify(v));return v}
export const adminApi={
  demoToken:DEMO_TOKEN,
  login:async(email:string,password:string)=>{if(email==="testemail"&&password==="testpassword")return {success:true,data:{token:DEMO_TOKEN,admin:{name:"Client Demo Admin",email,role:"admin"}}};return request<any>("/auth/admin/login",{method:"POST",body:JSON.stringify({email,password})})},
  products:async(t:string)=>isDemo(t)?{success:true,data:products()}:request<any>("/admin/products",{headers:{Authorization:"Bearer "+t}}),
  createProduct:async(t:string,b:any)=>{if(isDemo(t)){const id=Date.now(),c=categories().find(x=>x.id===b.categoryId),p:AdminProduct={id,name:b.name,description:b.description,price:b.price,discount:b.discount,brand:b.brand,status:b.status,category_id:b.categoryId,category_name:c?.name,images:[],variants:[]};saveProducts([p,...products()]);return{success:true,data:p}}return request("/admin/products",{method:"POST",headers:{Authorization:"Bearer "+t},body:JSON.stringify(b)})},
  updateProduct:async(t:string,id:number,b:any)=>{if(isDemo(t)){const a=products(),i=a.findIndex(x=>x.id===id);if(i<0)throw Error("Product not found");const c=categories().find(x=>x.id===b.categoryId);a[i]={...a[i],...b,category_name:c?.name};saveProducts(a);return{success:true,data:a[i]}}return request("/admin/products/"+id,{method:"PUT",headers:{Authorization:"Bearer "+t},body:JSON.stringify(b)})},
  archiveProduct:async(t:string,id:number)=>{if(isDemo(t)){saveProducts(products().map(p=>p.id===id?{...p,status:"archived"}:p));return{success:true}}return request("/admin/products/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+t}})},
  addVariant:async(t:string,pid:number,b:any)=>{if(isDemo(t)){const a=products(),p=a.find(x=>x.id===pid);if(!p)throw Error("Product not found");const v:any={id:Date.now(),product_id:pid,sku:b.sku,size:b.size||null,color:b.color||null,price:b.price??null,stock_quantity:Number(b.stockQuantity||0),status:"active"};p.variants=[...(p.variants||[]),v];saveProducts(a);return{success:true,data:v}}return request("/admin/products/"+pid+"/variants",{method:"POST",headers:{Authorization:"Bearer "+t},body:JSON.stringify(b)})},
  deleteVariant:async(t:string,id:number)=>{if(isDemo(t)){saveProducts(products().map(p=>({...p,variants:p.variants?.filter(v=>v.id!==id)})));return{success:true}}return request("/admin/variants/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+t}})},
  uploadImage:async(t:string,pid:number,file:File)=>{if(isDemo(t)){const a=products(),p=a.find(x=>x.id===pid);if(!p)throw Error("Product not found");const url=await new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>no(Error("Image read failed"));r.readAsDataURL(file)});p.images=[...(p.images||[]),{id:Date.now(),image_url:url,is_primary:!(p.images||[]).length}];saveProducts(a);return{success:true}}const f=new FormData();f.append("image",file);return request("/admin/products/"+pid+"/images",{method:"POST",headers:{Authorization:"Bearer "+t},body:f})},
  categories:async(t:string)=>isDemo(t)?{success:true,data:categories()}:request<any>("/categories",{headers:{Authorization:"Bearer "+t}}),
  addCategory:async(t:string,b:any)=>{if(isDemo(t)){const c={id:Date.now(),name:b.name,description:b.description||null};saveCategories([...categories(),c]);return{success:true,data:c}}return request("/categories",{method:"POST",headers:{Authorization:"Bearer "+t},body:JSON.stringify(b)})},
  deleteCategory:async(t:string,id:number)=>{if(isDemo(t)){saveCategories(categories().filter(c=>c.id!==id));return{success:true}}return request("/categories/"+id,{method:"DELETE",headers:{Authorization:"Bearer "+t}})},
  inventory:async(t:string,low=false)=>{if(isDemo(t)){const a=products().flatMap(p=>(p.variants||[]).map(v=>({variant_id:v.id,product_id:p.id,product_name:p.name,sku:v.sku,size:v.size,color:v.color,stock_quantity:v.stock_quantity,available_stock:v.stock_quantity,status:v.status||"active"})));return{success:true,data:low?a.filter(x=>x.available_stock<=5):a}}return request<{success:boolean;data:InventoryItem[]}>("/admin/inventory"+(low?"?lowStock=true":""),{headers:{Authorization:"Bearer "+t}})},
  setStock:async(t:string,id:number,n:number)=>{if(isDemo(t)){const a=products();for(const p of a){const v=p.variants?.find(x=>x.id===id);if(v){v.stock_quantity=n;saveProducts(a);return{success:true}}}throw Error("Inventory item not found")}return request("/admin/inventory/"+id,{method:"PUT",headers:{Authorization:"Bearer "+t},body:JSON.stringify({stockQuantity:n})})},
  orders:async(t:string,status="")=>{if(isDemo(t)){const live=JSON.parse(localStorage.getItem("demoOrders")||"[]");const combined=[...live.map((o:any)=>({id:o.id||Date.now(),order_number:o.orderNumber||o.order_number,customer_name:o.customerName||o.customer_name,customer_email:o.customerEmail||o.email,customer_phone:o.customerPhone||"",subtotal:o.subtotal||0,shipping_fee:o.shippingFee||o.shipping_fee||0,discount_amount:0,total_amount:o.totalAmount||o.total_amount||0,payment_status:o.paymentStatus||o.payment_status||"pending",order_status:o.orderStatus||o.order_status||"pending",created_at:o.createdAt||o.created_at,item_count:o.items?.length||0})),...orders()];const unique=Array.from(new Map(combined.map((o:any)=>[o.order_number,o])).values());let a=unique;if(status)a=a.filter((o:any)=>o.order_status===status);return{success:true,data:a}}const path="/admin/orders"+(status?"?status="+encodeURIComponent(status):"");const r:any=await request(path,{headers:{Authorization:"Bearer "+t}});return{success:true,data:Array.isArray(r.data)?r.data:r.data?.orders||[]}},
  order:async(t:string,id:number)=>{if(isDemo(t)){const live=JSON.parse(localStorage.getItem("demoOrders")||"[]");const created=live.find((x:any)=>Number(x.id)===id);if(created){const o={id:created.id,order_number:created.orderNumber||created.order_number,customer_name:created.customerName||created.customer_name,customer_email:created.customerEmail||created.email,customer_phone:created.customerPhone||"",shipping_address:created.shippingAddress||"",subtotal:created.subtotal||0,shipping_fee:created.shippingFee||created.shipping_fee||0,total_amount:created.totalAmount||created.total_amount||0,payment_status:created.paymentStatus||"pending",order_status:created.orderStatus||"pending"};return{success:true,data:{order:o,items:(created.items||[]).map((x:any,i:number)=>({id:x.id||i+1,product_name:x.product_name||x.name,sku:x.sku||"",size:x.size||"",color:x.color||"",quantity:x.quantity||1,unit_price:x.unit_price||x.price||0,total_price:Number(x.unit_price||x.price||0)*Number(x.quantity||1)}))}}}const o=orders().find(x=>x.id===id);if(!o)throw Error("Order not found");return{success:true,data:{order:o,items:[{id:1,product_name:"Tailored Oxford Shirt",sku:"DEMO-1-M",size:"M",color:"White",quantity:1,unit_price:2299,total_price:2299}]}}}return request<any>("/admin/orders/"+id,{headers:{Authorization:"Bearer "+t}})},
  setOrderStatus:async(t:string,id:number,status:string)=>{if(isDemo(t)){const a=orders(),o=a.find(x=>x.id===id);if(!o)throw Error("Order not found");o.order_status=status;saveOrders(a);return{success:true}}return request("/admin/orders/"+id+"/status",{method:"PUT",headers:{Authorization:"Bearer "+t},body:JSON.stringify({status})})}
};