CREATE TABLE users (
  id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'customer'
  CHECK (role IN ('customer','admin')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);