import {useEffect,useState} from "react";
import {Link,Route,Routes,useNavigate,useParams,useSearchParams} from "react-router-dom";
import {api,Product} from "./api";

const money=(v:number|string)=>`₹${Number(v||0).toLocaleString("en-IN")}`;
const Icon=({type}:{type:"search"|"bag"|"user"|"arrow"})=>{
 const p={width:17,height:17,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.4};
 if(type==="search")return <svg {...p}><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>;
 if(type==="user")return <svg {...p}><circle cx="12" cy="7" r="4"/><path d="M4 21v-1a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v1"/></svg>;
 if(type==="arrow")return <svg {...p}><path d="M5 12h13M13 6l6 6-6 6"/></svg>;
 return <svg {...p}><path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z"/><path d="M3 6h18M16 10a4 4 0 0 1-8 0"/></svg>;
};

function Header({count}:{count:number}){
 const [q,setQ]=useState("");const nav=useNavigate();
 return <header className="site-header"><div className="container header-main"><Link to="/" className="brand">DEMONSTATION</Link><div className="header-tools"><form className="search" onSubmit={e=>{e.preventDefault();if(q.trim())nav(`/products?search=${encodeURIComponent(q)}`)}}><Icon type="search"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="SEARCH"/></form><Link to="/admin" className="tool"><Icon type="user"/><span>ACCOUNT</span></Link><Link to="/cart" className="tool"><Icon type="bag"/><span>BAG ({count})</span></Link></div></div><nav className="container ribbon"><Link to="/products">COLLECTIONS</Link><Link to="/products?category=Men">MEN</Link><Link to="/products?category=Women">WOMEN</Link><Link to="/products?sort=newest">NEW ARRIVALS</Link><Link to="/products?sort=discount">SALE</Link><Link to="/track">ORDER TRACKING</Link></nav></header>;
}

function Card({p,index}:{p:Product,index:number}){
 const img=p.images?.find(x=>x.is_primary)?.image_url||p.images?.[0]?.image_url;
 return <Link to={`/products/${p.id}`} className="product-card" style={{animationDelay:`${index*45}ms`}}><div className="product-image">{img?<img src={img} alt={p.name}/>:<span>IMAGE PENDING</span>}<i>{String(index+1).padStart(2,"0")}</i></div><div className="product-meta"><div><small>{p.brand||"COLLECTION"}</small><h3>{p.name}</h3></div><strong>{money(p.price)}</strong></div></Link>;
}

function Home(){
 const [products,setProducts]=useState<Product[]>([]);
 useEffect(()=>{void api.getProducts("limit=8&sort=newest").then(r=>setProducts(r.data||[])).catch(()=>{})},[]);
 return <main><section className="hero"><div className="hero-media">{products[0]?.images?.[0]?.image_url&&<img src={products[0].images[0].image_url} alt=""/>}</div><div className="hero-shade"/><div className="container hero-copy"><small>COLLECTION / 01 — NEW SEASON</small><h1>FORM<br/><em>IN MOTION.</em></h1><p>Quiet structure. Considered essentials. A contemporary collection built for everyday movement.</p><Link className="light-link" to="/products">EXPLORE COLLECTION <Icon type="arrow"/></Link></div><div className="hero-foot"><span>SCROLL TO EXPLORE</span><span>01 / 05</span></div></section><section className="container statement section"><small>01 / BRAND STATEMENT</small><div><h2>Designed with restraint.<br/><em>Built with purpose.</em></h2><p>Premium essentials shaped around clean silhouettes, honest materials and a quieter approach to modern fashion.</p></div></section><section className="section collection"><div className="container section-head"><div><small>02 / COLLECTION INDEX</small><h2>NEW ARRIVALS</h2></div><Link className="text-link" to="/products">VIEW ALL <Icon type="arrow"/></Link></div><div className="container product-grid">{products.slice(0,4).map((p,i)=><Card p={p} index={i} key={p.id}/>)}</div></section><section className="container section editorial"><div><small>03 / EDITORIAL</small><h2>THE EVERYDAY<br/><em>UNIFORM.</em></h2><p>A focused wardrobe where utility meets proportion and every detail earns its place.</p><Link className="text-link" to="/products">SHOP THE EDIT <Icon type="arrow"/></Link></div><div className="editorial-image">{products[1]?.images?.[0]?.image_url&&<img src={products[1].images[0].image_url} alt=""/>}</div></section></main>;
}

function Products(){
 const [params,setParams]=useSearchParams();const [items,setItems]=useState<Product[]>([]);const [error,setError]=useState("");const q=params.get("search")||"";const category=params.get("category")||"";const sort=params.get("sort")||"newest";
 const load=async()=>{try{setError("");const s=new URLSearchParams();if(q)s.set("search",q);if(category)s.set("category",category);s.set("sort",sort);s.set("limit","50");setItems((await api.getProducts(s.toString())).data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load products")}};
 useEffect(()=>{void load()},[q,category,sort]);
 return <main className="container section catalog"><div className="section-head"><div><small>CATALOG / ALL PIECES</small><h1>THE COLLECTION</h1></div><span>{items.length} PIECES</span></div><div className="catalog-tools"><form className="catalog-search" onSubmit={e=>{e.preventDefault();const v=(e.currentTarget.elements.namedItem("q") as HTMLInputElement).value;setParams(p=>{v?p.set("search",v):p.delete("search");return p})}}><Icon type="search"/><input name="q" defaultValue={q} placeholder="SEARCH COLLECTION"/></form><div className="filters">{["","Men","Women"].map(x=><button className={category===x?"active":""} key={x||"all"} onClick={()=>setParams(p=>{x?p.set("category",x):p.delete("category");return p})}>{x||"ALL"}</button>)}<select value={sort} onChange={e=>setParams(p=>{p.set("sort",e.target.value);return p})}><option value="newest">NEWEST</option><option value="price_low">PRICE LOW</option><option value="price_high">PRICE HIGH</option><option value="name">NAME</option><option value="discount">DISCOUNT</option></select></div></div>{error&&<p className="error">{error}</p>}{items.length?<div className="product-grid">{items.map((p,i)=><Card p={p} index={i} key={p.id}/>)}</div>:<div className="empty">NO PRODUCTS FOUND</div>}</main>;
}

function ProductPage({refresh}:{refresh:()=>void}){
 const {id}=useParams();const [p,setP]=useState<Product|null>(null);const [v,setV]=useState<number|null>(null);const [msg,setMsg]=useState("");const [error,setError]=useState("");
 useEffect(()=>{if(id)void api.getProduct(Number(id)).then(r=>{setP(r.data);setV(r.data.variants?.find(x=>Number(x.stock_quantity)>0)?.id??null)}).catch(e=>setError(e.message))},[id]);
 if(error)return <main className="container section"><p className="error">{error}</p></main>;if(!p)return <main className="container section">LOADING...</main>;
 const img=p.images?.find(x=>x.is_primary)?.image_url||p.images?.[0]?.image_url;const selected=p.variants?.find(x=>x.id===v);
 const add=async()=>{try{let c=localStorage.getItem("cartId");if(!c){c=(await api.createCart()).data.id;localStorage.setItem("cartId",c)}await api.addCartItem(c,p.id,v,1);setMsg("ADDED TO BAG");refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to add to cart")}};
 return <main className="container section detail"><div className="detail-image">{img&&<img src={img} alt={p.name}/>}</div><div className="detail-copy"><small>{p.brand||"COLLECTION"} / PRODUCT {p.id}</small><h1>{p.name}</h1><div className="price">{money(selected?.price??p.price)}</div><p>{p.description||"A considered essential from the current collection."}</p>{p.variants?.length?<><label>SELECT VARIANT</label><div className="variants">{p.variants.map(x=><button disabled={Number(x.stock_quantity)<=0} className={v===x.id?"active":""} key={x.id} onClick={()=>setV(x.id)}>{[x.size,x.color].filter(Boolean).join(" / ")||x.sku}</button>)}</div></>:null}<button className="add" onClick={()=>void add()}>ADD TO BAG <Icon type="arrow"/></button>{msg&&<p className="success">{msg}</p>}{error&&<p className="error">{error}</p>}<div className="notes"><p><b>SHIPPING</b>Delivery calculated at checkout.</p><p><b>RETURNS</b>Subject to store policy.</p></div></div></main>;
}

function Cart(){
 const [cart,setCart]=useState<any>();useEffect(()=>{const id=localStorage.getItem("cartId");if(id)void api.getCart(id).then(r=>setCart(r.data)).catch(()=>{})},[]);
 const items=cart?.items||[];return <main className="container section narrow"><small>BAG / CURRENT SELECTION</small><h1>YOUR BAG</h1>{!items.length?<div className="empty">YOUR BAG IS EMPTY</div>:<><div className="cart-list">{items.map((x:any)=><div className="cart-row" key={x.id}><div><b>{x.product_name||x.name||`PRODUCT #${x.product_id}`}</b><small>QTY {x.quantity}</small></div><strong>{money(Number(x.unit_price||x.price||0)*x.quantity)}</strong></div>)}</div><div className="cart-total">SUBTOTAL <b>{money(cart?.subtotal||0)}</b><Link className="add" to="/checkout">CHECKOUT <Icon type="arrow"/></Link></div></>}</main>;
}

function Checkout(){
 const nav=useNavigate();const [f,setF]=useState({customerName:"",customerEmail:"",customerPhone:"",shippingAddress:""});const [error,setError]=useState("");
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const cartId=localStorage.getItem("cartId");if(!cartId)throw Error("Your cart is empty.");const r=await api.createOrder({cartId,...f});localStorage.removeItem("cartId");nav("/confirmation",{state:r.data})}catch(x){setError(x instanceof Error?x.message:"Checkout failed")}};
 return <main className="container section narrow"><small>CHECKOUT / DELIVERY</small><h1>DELIVERY DETAILS</h1><form className="form" onSubmit={submit}>{Object.entries(f).map(([k,v])=><label key={k}>{k.replace("customer","").replace(/([A-Z])/g," $1").toUpperCase()}<input required value={v} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="add">CREATE ORDER <Icon type="arrow"/></button></form>{error&&<p className="error">{error}</p>}<p className="muted">Payment integration will be connected after the order flow is verified.</p></main>;
}

function Track(){const [n,setN]=useState(""),[e,setE]=useState(""),[r,setR]=useState<any>(),[err,setErr]=useState("");return <main className="container section narrow"><small>CLIENT SERVICE / ORDER STATUS</small><h1>TRACK ORDER</h1><form className="form" onSubmit={async x=>{x.preventDefault();try{setErr("");setR((await api.trackOrder(n,e)).data)}catch(z){setR(null);setErr(z instanceof Error?z.message:"Order not found")}}}><label>ORDER NUMBER<input required value={n} onChange={x=>setN(x.target.value)}/></label><label>EMAIL<input required type="email" value={e} onChange={x=>setE(x.target.value)}/></label><button className="add">TRACK ORDER <Icon type="arrow"/></button></form>{err&&<p className="error">{err}</p>}{r&&<pre>{JSON.stringify(r,null,2)}</pre>}</main>}

function Admin(){const [token,setToken]=useState(localStorage.getItem("adminToken")||""),[email,setEmail]=useState("admin@example.com"),[password,setPassword]=useState("Admin@12345"),[tab,setTab]=useState("products"),[data,setData]=useState<any[]>([]),[error,setError]=useState("");
 useEffect(()=>{if(!token)return;const req=tab==="products"?api.adminProducts(token):tab==="orders"?api.adminOrders(token):api.adminInventory(token);void req.then(r=>setData(r.data||[])).catch(e=>setError(e.message))},[token,tab]);
 if(!token)return <main className="container section narrow"><small>PRIVATE / ADMIN</small><h1>STORE ADMIN</h1><form className="form" onSubmit={async e=>{e.preventDefault();try{const r=await api.adminLogin(email,password);localStorage.setItem("adminToken",r.data.token);setToken(r.data.token)}catch(x){setError(x instanceof Error?x.message:"Login failed")}}}><label>EMAIL<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="add">LOGIN</button></form>{error&&<p className="error">{error}</p>}</main>;
 return <main className="container section"><div className="section-head"><div><small>PRIVATE / ADMIN PANEL</small><h1>CONTROL ROOM</h1></div><button onClick={()=>{localStorage.removeItem("adminToken");setToken("")}}>LOGOUT</button></div><div className="admin-tabs">{["products","orders","inventory"].map(x=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x.toUpperCase()}</button>)}</div>{error&&<p className="error">{error}</p>}<pre>{JSON.stringify(data,null,2)}</pre></main>;
}

function Footer(){return <footer><div className="container footer-grid"><div><span className="brand">DEMONSTATION</span><p>Contemporary essentials. Designed with restraint.</p></div><div><small>SHOP</small><Link to="/products">Collection</Link><Link to="/track">Track Order</Link></div><div><small>SERVICE</small><span>Shipping & Delivery</span><span>Returns</span><span>Client Care</span></div></div><div className="container copyright">© {new Date().getFullYear()} DEMONSTATION / E-COMMERCE</div></footer>}

export default function App(){const [count,setCount]=useState(0);const refresh=async()=>{const id=localStorage.getItem("cartId");if(!id)return setCount(0);try{const r=await api.getCart(id);setCount((r.data?.items||[]).reduce((s:number,x:any)=>s+Number(x.quantity||0),0))}catch{setCount(0)}};useEffect(()=>{void refresh()},[]);return <><Header count={count}/><Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:id" element={<ProductPage refresh={refresh}/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/track" element={<Track/>}/><Route path="/admin" element={<Admin/>}/><Route path="/confirmation" element={<main className="container section confirmation"><small>ORDER / CONFIRMED</small><h1>THANK YOU.</h1><p>Your order has been created successfully.</p><Link className="text-link" to="/products">CONTINUE SHOPPING <Icon type="arrow"/></Link></main>}/></Routes><Footer/></>}